# prometheus.yml
global:
  scrape_interval: 5s #Busca dados a cada 5 segundos

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

#Expor uma rota /metrics
  - job_name: 'app-votacao' # Nosso alvo de aplicação
    metrics_path: /metrics
    static_configs:
      - targets: ['app-votacao:5000']
